// Generated by `bun init`

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.png";
declare module "*.jpg";
declare module "*.webp";
declare module "*.jpeg";
declare module "*.gif";
declare module "*.svg";

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}

declare module "bun" {
  interface Env {
    BUN_PUBLIC_SERVER_URL: string;
  }
}

// Register the router instance for type safety
declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}
